In [15]:
# all the imports required for the project 
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [16]:
# read in the teams data from the csv file
teams = pd.read_csv('teams_data.csv')

teams = teams.drop(columns = ["logo"])
teams.head()

   team_id   country                      team
0    50138     Italy  FC Internazionale Milano
1    50124     Spain        Atlético de Madrid
2    50111   Austria             SK Sturm Graz
3    52816     Italy               Atalanta BC
4    50050  Scotland                 Celtic FC

In [26]:
# read in the players_data from the csv file 
players = pd.read_csv("DAY_4/players_data.csv")

# we drop the weight, player image and height columns as we will not be using these in our analysis and they contain plenty of missing values
# we drop the position column as this has many blank values and field position provides us the data we need for looking at countries that specialise in certain areas of the field
players = players.drop(columns = ["position", "player_image", "weight(kg)", "height(cm)"])

players.head()

# rename team_id cloumn to match teams df for merging 
players = players.rename(columns = {"id_team" : "team_id"})

In [ ]:
# read in the key stats from the csv file 

key_stats = pd.read_csv("DAY_4/key_stats_data.csv")

key_stats.head()

,id_player,distance_covered(km/h),top_speed,minutes_played,matches_appareance
0,250016833,43.71,30.35,360.0,4.0
1,250105927,41.94,34.55,360.0,4.0
2,250121533,38.39,35.47,360.0,4.0
3,250121294,46.61,32.26,360.0,4.0
4,250160436,44.67,33.39,360.0,4.0

In [19]:
# gather some more info on the data frames we now have
players.info()

teams.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 908 entries, 0 to 907
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_player       908 non-null    int64
 1   player_name     908 non-null    object
 2   nationality     908 non-null    object
 3   field_position  908 non-null    object
 4   age             908 non-null    int64
 5   id_team         908 non-null    int64
dtypes: int64(3), object(3)
memory usage: 42.7+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   team_id  36 non-null     int64
 1   country  36 non-null     object
 2   team     36 non-null     object
dtypes: int64(1), object(2)
memory usage: 996.0+ bytes

In [ ]:
# get info about key stats
key_stats.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 908 entries, 0 to 907
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id_player               908 non-null    int64
 1   distance_covered(km/h)  727 non-null    float64
 2   top_speed               727 non-null    float64
 3   minutes_played          727 non-null    float64
 4   matches_appareance      727 non-null    float64
dtypes: float64(4), int64(1)
memory usage: 35.6 KB

id_player                 908
distance_covered(km/h)    908
top_speed                 908
minutes_played            908
matches_appareance        908
dtype: int64

In [21]:
# get unique values for field position column 
# this gives us the option to group players by position for analysis
players.field_position.unique()

array(['Forward', 'Midfielder', 'Defender', 'Goalkeeper'], dtype=object)

In [28]:
# merge the players, key_stats and teams data frames into on data frame

df_merged = pd.merge(players, key_stats, how = "inner", on = "id_player")

team_player_stats = pd.merge(df_merged, teams, how = "left", on = "team_id")

team_player_stats.head()

,id_player,player_name,nationality,field_position,age,team_id,distance_covered(km/h),top_speed,minutes_played,matches_appareance,country,team
0,250016833,Harry Kane,England,Forward,31,50037,43.71,30.35,360.0,4.0,Germany,FC Bayern München
1,250105927,Viktor Gyökeres,Sweden,Forward,26,50149,41.94,34.55,360.0,4.0,Portugal,Sporting Clube de Portugal
2,250121533,Vinícius Júnior,Brazil,Forward,24,50051,38.39,35.47,360.0,4.0,Spain,Real Madrid C.F.
3,250121294,Tijjani Reijnders,Netherlands,Midfielder,26,50058,46.61,32.26,360.0,4.0,Italy,AC Milan
4,250160436,Maghnes Akliouche,France,Midfielder,22,50023,44.67,33.39,360.0,4.0,France,AS Monaco

In [29]:
team_player_stats.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 908 entries, 0 to 907
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id_player               908 non-null    int64
 1   player_name             908 non-null    object
 2   nationality             908 non-null    object
 3   field_position          908 non-null    object
 4   age                     908 non-null    int64
 5   team_id                 908 non-null    int64
 6   distance_covered(km/h)  727 non-null    float64
 7   top_speed               727 non-null    float64
 8   minutes_played          727 non-null    float64
 9   matches_appareance      727 non-null    float64
 10  country                 908 non-null    object
 11  team                    908 non-null    object
dtypes: float64(4), int64(3), object(5)
memory usage: 85.3+ KB